name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches:
      - main
     
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: sanchaljustgrow
      IMAGE_FRONTEND: sanchaljustgrow/real-estate-frontend
      IMAGE_BACKEND: sanchaljustgrow/real-estate-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sanchaljustgrow
          password:  dckr_pat_T4IK4aMULkMBrfv2h1GYaZv2sAI

      - name: Set version tag
        id: vars
        run: |
          BRANCH=${GITHUB_REF##*/}
          SHORT_SHA=${GITHUB_SHA::7}
          echo "TAG=${BRANCH}-${SHORT_SHA}" >> $GITHUB_ENV
          echo "TAG=${BRANCH}-${SHORT_SHA}"

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend-fastify
          file: ./backend-fastify/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_BACKEND }}:latest
            ${{ env.IMAGE_BACKEND }}:${{ env.TAG }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_FRONTEND }}:latest
            ${{ env.IMAGE_FRONTEND }}:${{ env.TAG }}
